import type { TechnologyId } from '../data/technologies';

export type Language = 'es' | 'en';

export type Localized<T = string> = Record<Language, T>;

export type ProjectCategory = 'web' | 'games';

export type ProjectStatus = 'live' | 'upcoming';

export type ProjectRepository = { visibility: 'public'; url: string } | { visibility: 'private' };

export interface ProjectScreenshot {
  /** File name (without extension) generated by `npm run images` in public/projects. */
  file: string;
  alt: Localized;
  /** CSS object-position used when the card crops the screenshot. Defaults to center. */
  focus?: string;
}

export interface Project {
  id: string;
  name: string;
  category: ProjectCategory;
  status: ProjectStatus;
  /** Display order. Every project has the same visual hierarchy. */
  order: number;
  tagline: Localized;
  description: Localized;
  features: Localized<readonly string[]>;
  /** Up to four technologies shown on the card. */
  cardTechnologies: readonly TechnologyId[];
  /** Full list shown in the detail view. */
  technologies: readonly TechnologyId[];
  links: {
    demo?: string;
    repository: ProjectRepository;
  };
  screenshot: ProjectScreenshot;
}
